/*
 * 	ultrasonic.c
 *	Description: source file of UltraSonic Driver
 *  Created on: Mar 1, 2024
 * 	Author: AbdElRahman Khalifa
 */

#include"ultrasonic.h"
#include"icu.h"
#include"gpio.h"
#include<util/delay.h>

#include"lcd.h"

static volatile uint8 cnt;
static volatile uint16 distanceInCM, risingEdgeTime, fallingEdgeTime;

/*
 * Description:
 * 	-Initialize the ICU driver as required
 * 	-Setup the ICU call back function
 * 	-Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void) {
	/* configure ICU driver as required */
	ICU_ConfigType configuration = { ULTRASONIC_ICU_PRESCALLER, RAISING };
	ICU_init(&configuration);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup the direction for the trigger pin as output */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,
			ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);

}

/*
 * Description:
 * 	-Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void) {
	/* Send Logic hight to trigger pin for 10 us */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID,
			LOGIC_HIGH);
	_delay_us(10);

	/* clear trigger pin */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID,
			LOGIC_LOW);
}

/*
 * Description:
 * 	-Send the trigger pulse by using Ultrasonic_Trigger function
 * 	-Start the measurements by the ICU from this moment
 *
 * 	Return: The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void) {
	/* initialize edge of ICU and Timer counter and counter with 0 */
	cnt = 0;
	ICU_clearTimerValue();
	ICU_setEdgeDetectionType(RAISING);

	/* start Ultrasonic device */
	Ultrasonic_Trigger();

	/* waiting until we get the result using polling busy waiting */
	while (cnt != 2);

	return distanceInCM;
}

/*
 * Description:
 * 	-This is the call back function called by the ICU driver.
 * 	-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void) {
	cnt++;

	if (cnt == 1) {
		/* get the first rising edge and wait until next falling at which the result is ready */
		risingEdgeTime = ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(FALLING);
	} else {
		/* calculate the distance in cm */
		fallingEdgeTime = ICU_getInputCaptureValue();

		distanceInCM = ((fallingEdgeTime - risingEdgeTime)
				* (ULTRASONIC_TIME_RESOLUTION) * 170) * 100;
	}
}
